In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2],[3,4],[5,6]])
print(a)

[1 2 3]


In [2]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


## Number of array dimensions ndim

In [3]:
b.ndim

2

In [4]:
a.ndim

1

## Tuple of array dimensions.

In [7]:
a.shape
b.shape

(3, 2)

In [6]:
b.shape

(3, 2)

In [8]:
a.shape

(3,)

## Data-type of the array’s elements

In [9]:
a.dtype

dtype('int32')

## Create an array

In [10]:
c = np.array([2.3,3.3,4.3])
print(c)
c.dtype

[2.3 3.3 4.3]


dtype('float64')

## Length of one array element in bytes

In [11]:
a.itemsize

4

In [12]:
b.itemsize

4

In [13]:
c.itemsize

8

## Number of elements in the array

In [14]:
a.size
b.size
c.size

3

## Return a new array of given shape and type, filled with zeros

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Return a new array of given shape and type, filled with ones

In [17]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.ones((2,4,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

## Return a new array of given shape and type, filled with fill_value

In [20]:
np.full((2,3), 77)

array([[77, 77, 77],
       [77, 77, 77]])

## Random values in a given shape.

In [21]:
np.random.rand(4,2)

array([[0.47329712, 0.16623091],
       [0.14976722, 0.63006424],
       [0.09205308, 0.99698383],
       [0.89354636, 0.35363866]])

## Return random integers from low (inclusive) to high (exclusive)

In [22]:
np.random.randint(7, size=(3,3))

array([[3, 4, 6],
       [6, 6, 5],
       [4, 1, 1]])

In [23]:
np.random.randint(6, size=(3,3))

array([[5, 2, 0],
       [0, 4, 5],
       [2, 3, 2]])

## Create more than one dimension:

In [24]:
a = np.array([[1,2,3], [2,3,4], [3,4,5]])
print(a)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


## Number of array dimensions ndim for 2D Array

In [25]:
a.ndim

2

## Tuple of array dimensions 2D array

In [26]:
a.shape

(3, 3)

## Indexing

In [27]:
a[2,2]

5

In [28]:
a[2,1]

4

In [29]:
print(a)
a[1,:]

[[1 2 3]
 [2 3 4]
 [3 4 5]]


array([2, 3, 4])

In [30]:
print(a)
a[:,0]

[[1 2 3]
 [2 3 4]
 [3 4 5]]


array([1, 2, 3])

In [31]:
a[:,1]

array([2, 3, 4])

In [32]:
a[0, 1:-1:2]

array([2])

In [33]:
a = np.array([1,2,3])
b = a
b[1] = 77
print(a)
print(b)

[ 1 77  3]
[ 1 77  3]


In [34]:
c = np.array([1,2,3])
d = c.copy()
d[1] = 77
print(c)
print(d)

[1 2 3]
[ 1 77  3]


## Operations in the array

In [35]:
a = np.array([1,2,3,4])
print(a + 2)
print(a * 2)
print(a - 2)
print(a / 2)

[3 4 5 6]
[2 4 6 8]
[-1  0  1  2]
[0.5 1.  1.5 2. ]


In [36]:
b = np.array([1,2,3,4])
a + b

array([2, 4, 6, 8])

In [37]:
a * 2
print(a + b)

[2 4 6 8]


In [38]:
a * 3

array([ 3,  6,  9, 12])

## Trigonometric sine, element-wise. np.sin()

In [39]:
a = np.array([0,1,2,3,4])
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Trigonometric cos, element-wise. np.cos()

In [40]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Matrix product of two arrays. np.matmul()

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 3)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

## The identity array is a square array with ones on the main diagonal. np.identity() and Compute the determinant of an array. np.linalg.det()

In [42]:
c = np.identity(4)
np.linalg.det(c)

1.0

In [43]:
stat = np.array([[1,2,3], [4,5,6]])
np.max(stat)

6

In [44]:
np.min(stat)

1

In [45]:
print(stat)

[[1 2 3]
 [4 5 6]]


In [46]:
np.sum(stat, axis = 0)

array([5, 7, 9])